### PR TITLE
fix(swarm-node-remove): move query parameter to the right place

### LINKED ISSUE #508: Swarm.RemoveNodeAsync() fails because query parameters not passed correctly
**Output of `dotnet --info`:**

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**What version of Docker.DotNet?:**

```
3.125.4
```

**Steps to reproduce the issue:**
1. Call `await client.Swarm.RemoveNodeAsync("4vt9cdng72j9ff0ec6cmq2bkt", false)`

**What actually happened?:**
Exception because the query parameter `?force=False` is appended to the node ID:
```
Docker.DotNet.DockerApiException: Docker API responded with status code=NotFound, response={"message":"node 4vt9cdng72j9ff0ec6cmq2bkt?force=False not found"}

   at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
   at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
   at Docker.DotNet.SwarmOperations.Docker.DotNet.ISwarmOperations.RemoveNodeAsync(String id, Boolean force, CancellationToken cancellationToken)
```

**What did you expect to happen?:**
Node should be correctly removed.

**Additional Information:**
Possible fix, see #509

### PR DESCRIPTION
**Pull request by lippertmarkus**
This fixes #508.

As you use generated models, you need to replace my manually created class `NodeRemoveParameters` with your generated one accordingly.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/Docker.DotNet?pullRequest=509) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/Docker.DotNet?pullRequest=509) before we can accept your contribution.<br/><br/>:x: lippertmarkus [sign now](https://cla.dotnetfoundation.org/dotnet/Docker.DotNet?pullRequest=509)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/Docker.DotNet?pullRequest=509) it.</sub>

**Review by jterry75 — APPROVED** [review]
LGTM

**Comment by jterry75** [comment]
@galvesribeiro - PTAL. I'm ok with this not being generated since we will move away from that golang model anyways

**Comment by galvesribeiro** [comment]
Ok cool, lets move with it for now.

**Pull request merged**
