### PR TITLE
Update ContainerLogsParameters.Generated.cs

### PR DESCRIPTION
**Pull request by 13750573877**
Added missing until parameter

### CODE REVIEW

**Comment by HofmeisterAn** [comment]
I assume this should be done via `specgen` for a specific API version. The model classes are generated.

**Comment by galvesribeiro** [comment]
Yes, you need to update the specimen and not those files.

**Comment by HofmeisterAn** [comment]
I'll prepare the update with `specgen`. @galvesribeiro I noticed that e.g. this model class is part of `modeldefs.go` and not generated from the Docker API sources. Do I need to update those types by hand? Then I'll compare all types in the file agains the Docker API.

**Comment by galvesribeiro** [comment]
Yep that is the idea.

**Pull request closed without merging**
