### PR TITLE
Bugfix/578 allow chunked read stream write operations

### PR DESCRIPTION
**Pull request by HofmeisterAn**
Relates to #578. FYI @JonasBenz.

### CODE REVIEW

**Comment by JonasBenz** [comment]
> Relates to #578. FYI @JonasBenz.

Oh wow, thanks a lot for your effort.

**Comment by HofmeisterAn** [comment]
@galvesribeiro Is there anything against adopting the changes, see #581, #578, #554?

**Comment by galvesribeiro** [comment]
No. I believe they are good. Please rebase it on the main branch and force push and we can merge it to push a release.

Thanks!

**Comment by HofmeisterAn** [comment]
> No. I believe they are good. Please rebase it on the main branch and force push and we can merge it to push a release.
> 
> Thanks!

Great, thanks a lot 🙏. I'll rebase and push the changes tomorrow.

**Comment by HofmeisterAn** [comment]
I have added my changes that refactors the `TestFixture` too. The fixture now uses `IAsyncLifetime` and the async API. The test classes now access the fixture properties consistently.

**Comment by HofmeisterAn** [comment]
@galvesribeiro Is there anything missing? Could you adopt the changes, please?

Just let me know if I can take care of any specific following task, otherwise I will take a look at another open pull requests or issue.

**Comment by galvesribeiro** [comment]
Sorry for the delay. LGTM. Is there any other PR you wanna go with the same build?

**Review by galvesribeiro — APPROVED** [review]
LGTM

**Comment by HofmeisterAn** [comment]
> Sorry for the delay. LGTM. Is there any other PR you wanna go with the same build?

No problem. No, not for now. Having the last two PRs helps us a lot to continue. I’ll look through the other PRs and issues afterwards.

**Pull request merged**
