### PR TITLE
Documented container and image operation methods.

### PR DESCRIPTION
**Pull request by Emdot**
Updated the method header documentation to be more relevant to a .NET consumer, rather than being in terms of the underlying Docker Engine API calls. This covers IContainerOperations and IImageOperations.

If this is acceptable I'll plan to document more.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/Docker.DotNet?pullRequest=490) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/Docker.DotNet?pullRequest=490) before we can accept your contribution.<br/><br/>:x: Emdot [sign now](https://cla.dotnetfoundation.org/dotnet/Docker.DotNet?pullRequest=490)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/Docker.DotNet?pullRequest=490) it.</sub>

**Review by jterry75 — APPROVED** [review]
Wow thank you very much!

**Comment by Emdot** [comment]
Looks like this is ready to merge.

**Comment by jterry75** [comment]
@galvesribeiro - PTAL. LGTM

**Review by galvesribeiro — APPROVED** [review]
LGTM. Thanks!

**Comment by dgvives** [comment]
Just seen this, it was merged before I had the chance. 
@Emdot I encourage you to continue with so fine contributions

**Comment by Emdot** [comment]
Thank you!

**Pull request merged**
